### ISSUE TITLE
Display issue with Exterior Size fields on player side

### ISSUE THREAD

**Issue by GwaihirScout** [bmos/FG-PFRPG-Extraplanar-Containers#4] opened 2021-06-29 21:36 UTC
Looks fine on the GM side.

![unknown](https://user-images.githubusercontent.com/82128268/123870377-deb72b80-d8f7-11eb-873b-4f26a29bd05d.png)

**Comment by bmos** [comment] 2021-07-01 21:22
Thanks for reporting this!

**Comment by bmos** [comment] 2021-07-01 21:27
What extensions are you using?
I'm not seeing this when used on its own.

**Comment by GwaihirScout** [comment] 2021-07-02 22:41
Haven't had time to get a player to test it, but I think the issue may be in combination with the Enhanced Items extension. I missed that one earlier, and I think it's the only one I had on that affects items.

**Comment by bmos** [comment] 2021-07-03 14:00
Ah, that would make sense! I've been meaning to rewrite the script in that which handles field visibility.

**Comment by bmos** [comment] 2021-08-31 12:20
I am now unable to reproduce this issue and believe it has been fixed in Enhanced Items. If this is not the case, please comment here and I will re-open the issue or post a new Issue.

**Closed as completed by bmos** 2021-08-31 12:20 UTC
Labels: compatibility
